openapi: 3.0.3
info:
  title: WASAText
  description: |-
    This OpenAPI document describes APIs for the project "WASAText".

    Student: Nazerke Kulenova
    Matricola: 2046996
    E-mail: kulenova.2046996@studenti.uniroma1.it
    
  version: "1.0.2"

tags:
  - name: login
    description: Handles user sign-in and authentication requests
  - name: message
    description: Responsible for sending, retrieving, and managing chat messages
  - name: comment
    description: Supports adding, viewing, and interacting with comments
  - name: group
    description: Manages group creation, membership, and interactions
  - name: user
    description: Manages user accounts, profiles, and user-related actions
  - name: conversation
    description: Provides functionality for individual conversations and chat sessions

security:
  - BearerAuth: []

paths:
  /session:
    post:
      tags:
        - login
      summary: Authenticates the user
      description: |-
        If there is a no such user, then unique identifier is provided.
        If the account exists, the identifier for that user is returned.
      operationId: doLogin
      security: []
      requestBody:
        description: User details (name and photo in base64)
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '201':
          description: Login completed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
              example:
                identifier: "user123456abc"

  /users/photo:
    get:
      tags:
        - user
      summary: Fetches the photo of the currently logged-in user
      description: Returns the full User object (id, name and photo in base64)
      operationId: getMyPhoto
      security:
        - BearerAuth: []
      responses:
        '200':
          description: User photo fetched successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                id: "user123"
                name: "Nazerke"
                photo: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="
    put:
      tags:
        - user
      summary: Updates the profile photo of the authenticated user
      description: Saves the new photo and returns the updated user details
      operationId: setMyPhoto
      security:
        - BearerAuth: []
      requestBody:
        description: New photo (JPEG or PNG) in base64
        required: true
        content:
          image/png:
            schema:
              type: string
              description: PNG image file (base64)
              pattern: '^[A-Za-z0-9+/]+={0,2}$'
              minLength: 1
              maxLength: 10485760
          image/jpeg:
            schema:
              type: string
              description: JPEG image file (base64)
              pattern: '^[A-Za-z0-9+/]+={0,2}$'
              minLength: 1
              maxLength: 10485760
      responses:
        '200':
          description: Photo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                id: "user123"
                name: "Nazerke"
                photo: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="

  /users/name:
    put:
      tags:
        - user
      summary: Changes the username of the logged-in user
      description: Updates the user's username
      operationId: setMyUserName
      security:
        - BearerAuth: []
      requestBody:
        description: New username
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: Username updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                id: "user123"
                name: "NewName"
                photo: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="

  /conversations:
    get:
      tags:
        - conversation
      summary: Returns all conversations associated with the logged-in user
      description: Fetches conversations.
      operationId: getMyConversations
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Successfully returns the user's conversations
          content:
            application/json:
              schema:
                type: object
                description: Contains a list of conversations.
                required:
                  - conversations
                properties:
                  conversations:
                    type: array
                    description: List of conversations
                    minItems: 0
                    maxItems: 1000
                    items:
                      $ref: '#/components/schemas/ConversationDetailsSummary'
              example:
                conversations:
                  - id: "conv123"
                    name: "Group Chat"
                    members:
                      - "user123"
                      - "user456"
                    conversationPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="
                    lastMessage:
                      id: "message123"
                      senderId: "user456"
                      senderName: "Aruzhan"
                      content: "Hello!"
                      timestamp: "2025-11-20T10:00:00Z"
                      attachment: ""
                      reactionCount: 0
                      reactingUserIds: []
    post:
      tags:
        - conversation
      summary: Starts a new direct conversation
      description: Creates a direct one-on-one conversation between two users if it doesn’t already exist, then returns its details.
      operationId: startConversation
      security:
        - BearerAuth: []
      requestBody:
        description: JSON object that contains the sender and receiver identifiers.
        required: true
        content:
          application/json:
            schema:
              type: object
              description: Data required to start a direct chat.
              required:
                - senderId
                - recipientId
              properties:
                senderId:
                  type: string
                  description: ID of the sender.
                  example: "user123"
                  pattern: '^[a-zA-Z0-9_]+$'
                  minLength: 1
                  maxLength: 50
                recipientId:
                  type: string
                  description: ID of the recipient.
                  example: "user456"
                  pattern: '^[a-zA-Z0-9_]+$'
                  minLength: 1
                  maxLength: 50
      responses:
        '201':
          description: Conversation was created successfully and conversation data is returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationDetails'
              example:
                id: "conv123"
                name: "Group Chat"
                members:
                  - "user123"
                  - "user456"
                conversationPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="
                lastMessage:
                  id: "message789"
                  senderId: "user456"
                  senderName: "Aruzhan"
                  content: "Hello!"
                  timestamp: "2025-11-20T10:00:00Z"
                  attachment: ""
                  reactionCount: 0
                  reactingUserIds: []
                messages: []

  /conversations/{conversationId}:
    get:
      tags:
        - conversation
      summary: Fetches details of a specific conversation by ID
      description: Fetches conversation details.
      operationId: getConversation
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          description: ID of the conversation.
          schema:
            type: string
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
      responses:
        '200':
          description: Conversation details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationDetails'
              example:
                id: "conv123"
                name: "Group Chat"
                members:
                  - "user123"
                  - "user456"
                conversationPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="
                lastMessage:
                  id: "message789"
                  senderId: "user456"
                  senderName: "Aruzhan"
                  content: "Hello!"
                  timestamp: "2025-11-20T10:00:00Z"
                  attachment: ""
                  reactionCount: 0
                  reactingUserIds: []
                messages: []

  /conversations/{conversationId}/message:
    post:
      tags:
        - message
      summary: Creates and sends a message in a conversation
      description: Sends a message using multipart/form-data.
      operationId: sendMessage
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          description: ID of the conversation.
          schema:
            type: string
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
      requestBody:
        description: Form data containing message content and an attachment if needed.
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              description: Form data for sending a message.
              properties:
                content:
                  type: string
                  description: The content of the message.
                  example: "Hello, world!"
                  pattern: '^.*$'
                  minLength: 1
                  maxLength: 1000
                attachment:
                  type: string
                  description: Optional image attachment (JPEG, PNG, or GIF) in base64.
                  example: ""
                  pattern: '^[A-Za-z0-9+/]*={0,2}$'
                  minLength: 0
                  maxLength: 10485760
      responses:
        '201':
          description: Message sent successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
              example:
                id: "message123"
                senderId: "user123"
                senderName: "Nazerke"
                content: "Hello, world!"
                timestamp: "2025-11-20T10:05:00Z"
                attachment: ""
                reactionCount: 0
                reactingUserIds: []

  /conversations/{conversationId}/message/{messageId}/forward:
    post:
      tags:
        - message
      summary: Sends an existing message to a different conversation.
      description: Forwards a specific message from one conversation to another.
      operationId: forwardMessage
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          description: ID of the conversation that contains the message to be forwarded.
          schema:
            type: string
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
        - name: messageId
          in: path
          required: true
          description: ID of the message to be forwarded.
          schema:
            type: string
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
      requestBody:
        description: JSON payload with target conversation ID.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForwardMessageRequest'
            example:
              targetConversationId: "conv456"
      responses:
        '201':
          description: Message forwarded successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
              example:
                id: "message111"
                senderId: "user123"
                senderName: "Nazerke"
                content: "Hello, world!"
                timestamp: "2025-11-20T10:05:00Z"
                attachment: ""
                reactionCount: 0
                reactingUserIds: []

  /conversations/{conversationId}/message/{messageId}:
    delete:
      tags:
        - message
      summary: Deletes a message
      description: Deletes a message from the conversation.
      operationId: deleteMessage
      security:
        - BearerAuth: []
      parameters:
        - name: conversationId
          in: path
          required: true
          description: ID of the conversation.
          schema:
            type: string
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
        - name: messageId
          in: path
          required: true
          description: ID of the message to delete.
          schema:
            type: string
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
      responses:
        '204':
          description: Message deleted successfully.

  /conversations/{conversationId}/message/{messageId}/comment:
    parameters:
      - name: conversationId
        in: path
        required: true
        description: ID of the conversation.
        schema:
          type: string
          pattern: '^[a-zA-Z0-9_]+$'
          minLength: 1
          maxLength: 50
      - name: messageId
        in: path
        required: true
        description: ID of the message to be commented.
        schema:
          type: string
          pattern: '^[a-zA-Z0-9_]+$'
          minLength: 1
          maxLength: 50
    post:
      tags:
        - comment
      summary: Adds a comment to a message
      description: Adds a comment to the messageID specified.
      operationId: commentMessage
      security:
        - BearerAuth: []
      requestBody:
        description: JSON payload with comment content.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCommentRequest'
      responses:
        '204':
          description: Comment added successfully.
    delete:
      tags:
        - comment
      summary: Removes a comment from a message
      description: Deletes a comment from the specified messageID.
      operationId: uncommentMessage
      security:
        - BearerAuth: []
      responses:
        '204':
          description: Comment deleted successfully.

  /search:
    get:
      tags:
        - conversation
        - user
      summary: Searches the users by username
      description: Searches the users by matching with query.
      operationId: searchUsers
      security:
        - BearerAuth: []
      parameters:
        - name: username
          in: query
          required: true
          description: Username query parameter
          schema:
            type: string
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
      responses:
        '200':
          description: a list of users that match the query.
          content:
            application/json:
              schema:
                type: array
                description: Array of User objects.
                minItems: 0
                maxItems: 1000
                items:
                  $ref: '#/components/schemas/User'
              example:
                - id: "user123"
                  name: "Nazerke"
                  photo: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="

  /groups:
    get:
      tags:
        - group
      summary: Retrieves the list of groups for the authenticated user
      description: Fetches groups.
      operationId: getMyGroups
      security:
        - BearerAuth: []
      responses:
        '200':
          description: List of groups.
          content:
            application/json:
              schema:
                type: object
                description: Contains a list of groups.
                required:
                  - groups
                properties:
                  groups:
                    type: array
                    description: List of groups.
                    minItems: 0
                    maxItems: 1000
                    items:
                      $ref: '#/components/schemas/Group'
              example:
                groups:
                  - id: "group123"
                    name: "Group Chat"
                    members:
                      - "user123"
                      - "user456"
                    groupPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="
    post:
      tags:
        - group
      summary: Creates a new group
      description: |-
        Creates a new group chat. The request should use multipart/form-data including the group name, a JSON string of member IDs (under membersJson), and a group image.
      operationId: createGroup
      security:
        - BearerAuth: []
      requestBody:
        description: data needed to create the group
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              description: Form data for group creation.
              properties:
                name:
                  type: string
                  description: Name of the group.
                  example: "Group Chat"
                  pattern: '^[a-zA-Z0-9_ ]+$'
                  minLength: 3
                  maxLength: 50
                membersJson:
                  type: string
                  description: A JSON string array of member IDs (including the creator).
                  example: '["user123","user456"]'
                  pattern: '^\[.*\]$'
                  minLength: 2
                  maxLength: 1000
                image:
                  type: string
                  description: Group image (JPEG or PNG) in basr 64.
                  example: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="
                  pattern: '^[A-Za-z0-9+/]*={0,2}$'
                  minLength: 1
                  maxLength: 10485760
      responses:
        '201':
          description: Group created successfully and returns the complete group object with its ID, name, members, and group photo.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
              example:
                id: "group123"
                name: "Group Chat"
                members:
                  - "user123"
                  - "user456"
                groupPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="

  /groups/{groupId}:
    get:
      tags:
        - group
      summary: Fetches details of specified groupID
      description: Fetches group details with members and group image.
      operationId: getGroup
      security:
        - BearerAuth: []
      parameters:
        - name: groupId
          in: path
          required: true
          description: ID of the group.
          schema:
            type: string
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
      responses:
        '200':
          description: Group details fetched successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
              example:
                id: "group123"
                name: "Group Chat"
                members:
                  - "user123"
                  - "user456"
                groupPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="
    delete:
      tags:
        - group
      summary: Leaves a group
      description: Removes the logged-in user from the specified groupID.
      operationId: leaveGroup
      security:
        - BearerAuth: []
      parameters:
        - name: groupId
          in: path
          required: true
          description: ID of the group to leave.
          schema:
            type: string
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
      responses:
        '204':
          description: Left group successfully.
    post:
      tags:
        - group
      summary: Adds a user to a group
      description: Adds a user to the specified groupID.
      operationId: addToGroup
      security:
        - BearerAuth: []
      parameters:
        - name: groupId
          in: path
          required: true
          description: ID of the group.
          schema:
            type: string
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
      requestBody:
        description: JSON payload with the user ID to add.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddGroupMemberRequest'
      responses:
        '204':
          description: User added to group successfully.

  /groups/{groupId}/name:
    put:
      tags:
        - group
      summary: Updates the groupName.
      description: Updates the groupName.
      operationId: setGroupName
      security:
        - BearerAuth: []
      parameters:
        - name: groupId
          in: path
          required: true
          description: ID of the group.
          schema:
            type: string
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
      requestBody:
        description: New group name.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateGroupNameRequest'
      responses:
        '200':
          description: GroupName updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Group'
              example:
                id: "group123"
                name: "New Group Name"
                members:
                  - "user123"
                  - "user456"
                groupPhoto: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="
  /groups/{groupId}/photo:
    put:
      tags:
        - group
      summary: Updates the groupPhoto
      description: Updates the groupPhoto.
      operationId: setGroupPhoto
      security:
        - BearerAuth: []
      parameters:
        - name: groupId
          in: path
          required: true
          description: ID of the group.
          schema:
            type: string
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
      requestBody:
        description: New photo (JPEG or PNG) in base64.
        required: true
        content:
          image/png:
            schema:
              type: string
              description: PNG image file (base64)
              pattern: '^[A-Za-z0-9+/]*={0,2}$'
              minLength: 1
              maxLength: 10485760
          image/jpeg:
            schema:
              type: string
              description: JPEG image file (base64)
              pattern: '^[A-Za-z0-9+/]*={0,2}$'
              minLength: 1
              maxLength: 10485760
      responses:
        '200':
          description: Group photo updated successfully.
          content:
            application/json:
              schema:
                type: object
                description: Pop-up message for group photo update.
                required:
                  - message
                properties:
                  message:
                    type: string
                    description: Pop-up message.
                    example: "Group photo updated successfully"
                    pattern: '^.*$'
                    minLength: 1
                    maxLength: 100

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginRequest:
      type: object
      description: Structure of the data sent when a user logs in.
      required:
        - name
        - photo
      properties:
        name:
          type: string
          description: Username provided by the person signing in.
          example: "Nazerke"
          pattern: '^[a-zA-Z0-9_]+$'
          minLength: 3
          maxLength: 24
        photo:
          type: string
          description: A base64  profile picture for the user.
          example: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="
          pattern: '^[A-Za-z0-9+/]+={0,2}$'
          minLength: 1
          maxLength: 1000000

    LoginResponse:
      type: object
      description: Response schema for user login.
      properties:
        identifier:
          type: string
          description: The identifier of the logged-in user.
          example: "user123456abc"
          pattern: '^[a-zA-Z0-9_]+$'
          minLength: 1
          maxLength: 50

    UpdateUserRequest:
      type: object
      description: Request schema for updating user information.
      properties:
        name:
          type: string
          description: New username.
          example: "NewName"
          pattern: '^[a-zA-Z0-9_]+$'
          minLength: 3
          maxLength: 24

    User:
      type: object
      description: User schema.
      required:
        - id
        - name
        - photo
      properties:
        id:
          type: string
          description: Unique identifier of the user.
          example: "user123"
          pattern: '^[a-zA-Z0-9_]+$'
          minLength: 1
          maxLength: 50
        name:
          type: string
          description: Name of the user.
          example: "Nazerke"
          pattern: '^[a-zA-Z0-9_]+$'
          minLength: 3
          maxLength: 24
        photo:
          type: string
          description: User photo in base64.
          example: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="
          pattern: '^[A-Za-z0-9+/]+={0,2}$'
          minLength: 1
          maxLength: 1000000

    ConversationDetailsSummary:
      type: object
      description: A summary of a conversation between users.
      required:
        - id
        - name
        - members
      properties:
        id:
          type: string
          description: Unique identifier of the conversation.
          example: "conv123"
          pattern: '^[a-zA-Z0-9_]+$'
          minLength: 1
          maxLength: 50
        name:
          type: string
          description: Name of the conversation.
          example: "Group Chat"
          pattern: '^[a-zA-Z0-9_ ]+$'
          minLength: 1
          maxLength: 50
        members:
          type: array
          description: List of user IDs participating in the conversation.
          minItems: 1
          maxItems: 1000
          items:
            type: string
            description: User ID.
            example: "user123"
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
        conversationPhoto:
          type: string
          description: Base64 conversation photo (if any).
          example: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="
          pattern: '^[A-Za-z0-9+/]*={0,2}$'
          minLength: 0
          maxLength: 1000000
        lastMessage:
          $ref: '#/components/schemas/Message'

    ConversationDetails:
      title: "Conversation Details"
      type: object
      description: Detailed conversation schema.
      required:
        - id
        - name
        - members
        - messages
      properties:
        id:
          type: string
          description: Unique identifier of the conversation.
          example: "conv123"
          pattern: '^[a-zA-Z0-9_]+$'
          minLength: 1
          maxLength: 50
        name:
          type: string
          description: Name of the conversation.
          example: "Group Chat"
          pattern: '^[a-zA-Z0-9_ ]+$'
          minLength: 1
          maxLength: 50
        members:
          type: array
          description: List of user IDs participating in the conversation.
          minItems: 1
          maxItems: 1000
          items:
            type: string
            description: User ID.
            example: "user123"
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
        conversationPhoto:
          type: string
          description: Conversation photo in base64 (if any).
          example: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="
          pattern: '^[A-Za-z0-9+/]*={0,2}$'
          minLength: 0
          maxLength: 1000000
        lastMessage:
          $ref: '#/components/schemas/Message'
        messages:
          type: array
          description: List of messages in the conversation.
          minItems: 0
          maxItems: 1000
          items:
            $ref: '#/components/schemas/Message'

    Message:
      type: object
      description: A message sent in a conversation.
      required:
        - id
        - senderId
        - senderName
        - content
        - attachment
        - timestamp
        - reactionCount
        - reactingUserIds
      properties:
        id:
          type: string
          description: Unique identifier of the message.
          example: "message123"
          pattern: '^[a-zA-Z0-9_]+$'
          minLength: 1
          maxLength: 50
        senderId:
          type: string
          description: ID of the user who sent the message.
          example: "user456"
          pattern: '^[a-zA-Z0-9_]+$'
          minLength: 1
          maxLength: 50
        senderName:
          type: string
          description: Name of the sender.
          example: "Aruzhan"
          pattern: '^[a-zA-Z0-9 ]+$'
          minLength: 1
          maxLength: 50
        content:
          type: string
          description: Content of the message.
          example: "Hello, world!"
          pattern: '^.*$'
          minLength: 1
          maxLength: 1000
         attachment:
          type: string
          description: Base64 attachment (if any).
          example: ""
          pattern: '^[A-Za-z0-9+/]*={0,2}$'
          minLength: 0
          maxLength: 10485760
        timestamp:
          type: string
          format: date-time
          description: When the message was sent.
          example: "2025-11-20T10:05:00Z"
          minLength: 20
          maxLength: 29
        reactionNumber:
          type: integer
          description: Number of reactions on the message.
          example: 2
        reactingUserIds:
          type: array
          description: List of user IDs who reacted to this message.
          minItems: 0
          maxItems: 1000
          items:
            type: string
            example: "user123"
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
        replyTo:
          type: string
          description: ID of the message being replied to. Optional.
          example: ""
          pattern: '^[a-zA-Z0-9_]*$'
          minLength: 0
          maxLength: 50
        replyContent:
          type: string
          description: A preview of the message being replied to. Optional
          example: ""
          pattern: '^.*$'
          minLength: 0
          maxLength: 1000
        repliedMessageSenderName:
          type: string
          description: Name of the sender whose message is being replied. Optional
          example: ""
          pattern: '^[a-zA-Z0-9 ]*$'
          minLength: 0
          maxLength: 50
        replyAttachment:
          type: string
          description: Base64 attachment from the replied-to message. Optional
          example: ""
          pattern: '^[A-Za-z0-9+/]*={0,2}$'
          minLength: 0
          maxLength: 10485760
        status:
          type: string
          description: Shows whether the message is delivered/read.Included only if the message was not sent by logged-in user. Optional
          example: "✓"
          pattern: '^.*$'
          minLength: 0
          maxLength: 10

    ForwardMessageRequest:
      type: object
      description: Request body schema for forwarding a message.
      required:
        - targetConversationId
      properties:
        targetConversationId:
          type: string
          description: ID of the conversation where the message will be forwarded.
          example: "conv456"
          pattern: '^[a-zA-Z0-9_]+$'
          minLength: 1
          maxLength: 50
        forwarderName:
          type: string
          description: Name of the user forwarding the message. Optional
          example: "Nazerke"
          pattern: '^[a-zA-Z0-9 ]*$'
          minLength: 0
          maxLength: 50

    AddCommentRequest:
      type: object
      description: Request body schema to add a comment.
      required:
        - content
      properties:
        content:
          type: string
          description: The text of the comment.
          example: "Nice post!"
          pattern: '^.*$'
          minLength: 1
          maxLength: 500

    AddGroupMemberRequest:
      type: object
      description: Request body schema to add a group member.
      required:
        - userId
      properties:
        userId:
          type: string
          description: ID of the user that is added.
          example: "user789"
          pattern: '^[a-zA-Z0-9_]+$'
          minLength: 1
          maxLength: 50

    UpdateGroupNameRequest:
      type: object
      description: Request body schema to update the name of the group.
      required:
        - groupName
      properties:
        groupName:
          type: string
          description: New name of the group.
          example: "New Group Name"
          pattern: '^[a-zA-Z0-9_ ]+$'
          minLength: 3
          maxLength: 24

    Group:
      type: object
      description: Group schema.
      required:
        - id
        - name
        - members
      properties:
        id:
          type: string
          description: Unique identifier of the group.
          example: "group123"
          pattern: '^[a-zA-Z0-9_]+$'
          minLength: 1
          maxLength: 50
        name:
          type: string
          description: Name of the group.
          example: "Group Chat"
          pattern: '^[a-zA-Z0-9_ ]+$'
          minLength: 3
          maxLength: 50
        members:
          type: array
          description: List of user IDs that are members of the group.
          minItems: 1
          maxItems: 1000
          items:
            type: string
            description: User ID.
            example: "user123"
            pattern: '^[a-zA-Z0-9_]+$'
            minLength: 1
            maxLength: 50
        groupPhoto:
          type: string
          description: group photo in base64 (if any).
          example: "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8Xw8AAukB9oR5hW8AAAAASUVORK5CYII="
          pattern: '^[A-Za-z0-9+/]*={0,2}$'
          minLength: 0
          maxLength: 1000000



